# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659b92a94a76a222febb58e5ecf2048e024b907f087fa5197974354f3b665d4ec6bf430c139c8223c9e01b38015c7d5076ea5ffe82ce517c647c61cf28506376

test:
  secret_key_base: cf7c6272f833d4a5784a6e9b5708ba100787c8be34b95c6840029711c4a86c5d07500a3ec133731cb09af13bf5f495cc492817ce9d1843fb28177e999f9911c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
